tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#131313",
        surface: "#131313",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-variant": "#353534",
        primary: "#ffffff",
        "on-primary": "#31302d",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "on-surface-variant": "#c8c7be",
        outline: "#929189",
        "outline-variant": "#474741",
        secondary: "#ccc6ba",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "32px",
        "element-gap": "24px",
        margin: "64px",
        "container-max": "1440px",
        "section-gap": "160px",
      },
      fontFamily: {
        montserrat: ["Montserrat", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "display-xl": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
      },
    },
  },
};
